FROM node:12 as dependencies
WORKDIR /my-project
COPY package.json ./
RUN yarn install

FROM node:12 as builder
WORKDIR /my-project
COPY . .
COPY --from=dependencies /my-project/node_modules ./node_modules

EXPOSE 3000
CMD ["yarn", "dev"]